#!/usr/bin/env zsh
# kill all other processes

function logexit {
    print -P -- "$*" >&2
    exit 1
}

(($#<1)) && logexit "Usage: ${0:t} user [user ...]" 


function stopquestion() {
    print -n -- "$* (y/n): "
    read answer
    case $answer in
        y|Y) print -- "OK you've been warned!";;
        *) exit 0 ;;
    esac
}

local processlist
for victim in $@; do

    case $victim in
        $USER) stopquestion "Are you sure to kill your own processes?";;
        init|root) stopquestion "Are you sure to kill all '$victim' processes?";;
    esac
    
    processlist=( $processlist $(ps aux | awk '$1 == "'$victim'" {print $2}') )
    
    (($#processlist == 0)) && logexit "The user '$victim' doesn't run any process"

done

sudo kill -9 $processlist
